task_1 bfs
Nikita-Fast/high-performance-graph-analysis-course pull request #1
Opened 2023-03-11 18:08 UTC by Nikita-Fast

# Задача 1. Реализация обхода в ширину (BFS – LEVELS)
- [x] Используя pygraphblas реализовать функцию обхода ориентированного графа в ширину из заданной вершины. При этом организовать все вычисления в виде операций над векторами и матрицами.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [x] Функция возвращает массив, где для каждой вершины указано, на каком шаге она достижима. Стартовая вершина достижима на нулевом шаге, если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
    - Проверить, что тесты запускаются только на linux.

2023-03-11 19:32 UTC, Nikita-Fast commented
чтобы успеть к мягкому дедлайну сделал (возможно не лучший) фикс в файле run_tests.py для обеспечения работы тестов. Подробнее писал об этом в тг, где спрашивал о более качественном решении

2023-03-14 09:58 UTC, rustam-azimov requested changes

2023-03-14 09:58 UTC, rustam-azimov commented on project/bfs.py
> +    res_matrix = Matrix.dense(
Лучше Vector

2023-03-14 09:58 UTC, rustam-azimov commented on project/bfs.py
> +        was_mask.eadd(
Можно без was_mask обойтись. Вместо маски was_mask используйте res_matrix. Останавливаемся когда curr_front пустой.

2023-03-14 09:58 UTC, rustam-azimov commented on project/bfs.py
> +    curr_front = Matrix.sparse(types.BOOL, nrows=1, ncols=adjacency_matrix.ncols)
Тут тоже Vector

2023-03-14 09:58 UTC, rustam-azimov commented on project/bfs.py
> +    return list(res_matrix[0].vals)
Чтобы все работало, надо -1 в конце заполнить, после цикла. Тоже используя маску

2023-03-14 09:58 UTC, rustam-azimov commented on tests/test_bfs.py
> +        (
Лучше сразу реализовать функции, считывающие граф из файла и конвертирующие его в нужный формат.

2023-03-15 19:11 UTC, Nikita-Fast commented
В файле utils есть метод позволяющий построить оъект матрицу по данным извлеченным из json. Однако возникла проблема с использованием этой функции. В test_bfs.py есть закоментированный метод, который мне и хотелось сдать в качестве ответа на запрошенные вами изменения. Однако если тот тест раскоментировать, то при запуске все падает с ошибкой TypeError: the first argument must be callable. При этом сам объект матрицы нормально создается, а проблема словно возникает из-за того, что матрица создается не в коде теста. Поскольку проблему не получается исправить, то сдаю версию с неидельным тестом, который читает все с json, но по-прежнему сам создает матрицу, а не получает готовую

2023-03-18 07:37 UTC, rustam-azimov approved these changes
5 баллов. Проблема возможно в pygraphblas просто

2023-03-22 17:32 UTC, merged